services:
  comfyui:
    build:
      context: ./comfyui
      dockerfile: ../Dockerfile
    container_name: docker-comfyui
    restart: always
    ports:
      - '8188:8188'
    volumes:
      - ./comfyui:/ComfyUI
    logging:
      options:
        max-size: '200k'
        max-file: '10'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
